spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Disable web framework conflict
spring.main.web-application-type=reactive

# Route to auth service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://authservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Route to user service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://userservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# Actuator
management.endpoints.web.exposure.include=*